Comm=CreateObject("MSCOMMLib.MSComm") '首先创建一对象 
Comm.CommPort=2 '设定要使用的端口1～16 
Comm.Handshaking=0                         '见详解 
Comm.RThreshold=0 
Comm.Settings="9600,N,8,1" 
Comm.InputLen=0                            ' 
Comm.RTSEnable=False 
Comm.PortOpen=TRUE                         '设置完毕打开 
Comm.Output="hello,world"                 '发送string 
Comm.PortOpen=FALSE                         '使用完毕，关闭